### PR TITLE
Interpret missing TTL as 300 for Hetzner's API

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Apparently a missing TTL means 300.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
Hetzner API

### CODE REVIEW

**Review by markuman — CHANGES_REQUESTED** [review]
the docs needs also updated

**Comment by felixfontein** [comment]
Which docs?

**Comment by felixfontein** [comment]
That's totally unrelated to this PR, since that's the module UX, and not the API return value.

**Review by markuman — APPROVED** [review]

**Comment by felixfontein** [comment]
@markuman thanks for reviewing!

**Pull request merged**
