### PR TITLE
Add quote_txt and unquote_txt filters

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Adds filters `quote_txt` and `unquote_txt` for working with TXT records.

Ref: https://github.com/ansible-collections/community.general/pull/8227

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
quote_txt
unquote_txt

### CODE REVIEW

**Comment by alive1** [comment]
I'd really appreciate this functionality as I am currently experiencing an issue that this PR solves.

**Comment by samccann** [comment]
Does it need a changelog?

**Comment by felixfontein** [comment]
@samccann no, the `version_added: 2.9.0` should ensure one is created automatically.

**Comment by felixfontein** [comment]
@alive1 @samccann thanks!

**Comment by alive1** [comment]
@felixfontein Amazing work, thank you so much for doing it.
Not to be a bother - but since I'm not familiar with the projects release schedule, I have to ask: What is the timeline for the new filters to be widely available through ansible galaxy?

**Comment by felixfontein** [comment]
@alive1 you're welcome! I usually create a release 1-2 days before the next Ansible release, which is scheduled for next week Tuesday. (The reason is that I'd like the most current version of the public suffix list to be included.) So I'll make a release on Sunday or Monday.

**Comment by alive1** [comment]
Oh that's pretty clever. And fast!

Thank you again :)

**Pull request merged**
