### PR TITLE
DRAFT: Correct MPL-2.0 license identifier to MPL-2.0-no-copyleft-exception

### PR DESCRIPTION
**Pull request by gotmax23**
##### SUMMARY
Now that collections have started adopting REUSE, I was able to do a more thorough license review of the `ansible` package.

According to the SPDX license checker[0], the correct license identifier
here is MPL-2.0-no-copyleft-exception.

[0]: https://tools.spdx.org/app/check_license/

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
meta

##### ADDITIONAL INFORMATION

As far as I know, the MPL 2.0 is not compatible with the GPL without the copyleft exception and thus, and this file needs to be removed from the collection.

This also presents a problem for Fedora. Besides the fact that `MPL-2.0-no-copyleft-exception` has not yet been approved for Fedora (I think it should), the license compatibility issue would probably be a problem for us as well.

@richardfontana, are you able to chime in here?

### CODE REVIEW

**Comment by richardfontana** [comment]
@gotmax23 is this based on pasting the standard MPL-2.0 license file into the SPDX check-license tool? Asking because I myself have gotten confused about this point (given the limited adoption of MPL-2.0). The MPL-2.0 license text contains the text of the notice that you are supposed to use if you are selecting the non-default GPL-incompatibility feature, but this itself is not intended to signify that all uses of the standard MPL-2.0 license text are intended to select the property associated with MPL-2.0-no-copyleft-exception.

**Comment by richardfontana** [comment]
As an aside, the fact that this file has been placed under MPL-2.0 is kind of ridiculous.

**Comment by felixfontein** [comment]
@gotmax23 

> According to the SPDX license checker[0](https://tools.spdx.org/app/check_license/), the correct license identifier here is MPL-2.0-no-copyleft-exception.

I think this is wrong, since the list does not use “Incompatible With Secondary Licenses” Notice from Exhibit B of the MPL (https://www.mozilla.org/en-US/MPL/2.0/). According to https://spdx.org/licenses/MPL-2.0-no-copyleft-exception, `MPL-2.0-no-copyleft-exception` is for when Exhibit B is used. The list itself (https://publicsuffix.org/list/public_suffix_list.dat) does not mention Exhibit B, only:
```
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
```

@richardfontana I think I read somewhere that the list started as part of Mozilla/Firefox, and thus was probably covered by the MPL before it was moved out of the browser. I guess the main reason it's still licensed under MPL is that it would require too much effort to change the license.

**Comment by gotmax23** [comment]
I copied the license text into the SPDX license tool, and it determined that the correct identifier is MPL-2.0-no-copyleft-exception.

It seems that you are indeed correct. There is no file header or anything else that signifies this.

**Comment by gotmax23** [comment]
Sorry for the false alarm!

**Comment by felixfontein** [comment]
@gotmax23 thanks for checking!

**Comment by richardfontana** [comment]
Contextually we know (I'm pretty sure) that the Mozilla Foundation itself wouldn't invoke the "no-copyleft-exception" mechanism. I may submit an issue about this in the SPDX tools repository.

**Comment by richardfontana** [comment]
Submitted this issue: https://github.com/spdx/tools/issues/308

**Pull request closed without merging**
