### PR TITLE
Modernize controller-side Python code

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
- [x] Generali modernizations.
- [ ] ~~Make sure type hints are checked in CI.~~
- [ ] ~~Add type hints.~~

##### ISSUE TYPE
- Refactoring Pull Request

##### COMPONENT NAME
controller-side code

### CODE REVIEW

**Comment by felixfontein** [comment]
It looks like ansible-core's mypy test only runs for ansible-core and not for collections :( So the second point likely gets more complicated... (And in particular more annoying for contributors, since you cannot simply run `ansible-test sanity --docker -v` to cover the most important things.)

**Comment by felixfontein** [comment]
CC @oraNod

**Comment by oraNod** [comment]
> It looks like ansible-core's mypy test only runs for ansible-core and not for collections :( So the second point likely gets more complicated... (And in particular more annoying for contributors, since you cannot simply run `ansible-test sanity --docker -v` to cover the most important things.)

@felixfontein I've been asking around to see if there are any recommendations for collections maintainers. I haven't found anything so far. Excuse my ignorance but is it just the convenience of a single command to test the entire collection structure that is missing?

Maybe we could come up with a special mypy config for collections and then do something like this?

`mypy --config-file mypy.ini $(find ./plugins -name "*.py" -not -path "*/test/*")`

I'm not sure if that's a terrible idea or not...

**Comment by felixfontein** [comment]
> Excuse my ignorance but is it just the convenience of a single command to test the entire collection structure that is missing?

No, that's just one small part of it. There's also the issue of making it reproducable (i.e. use the same version of mypy everywhere), and providing a simple way to use it that includes installing dependencies.

Of course we could use a `requirements.txt` file with Dependabot updates, and some Makefile, nox, or tox script to run all the things. But that's just more config that has to be repeated in every collection. The nice thing about `ansible-test sanity --docker -v` (and the unit and integration test variants) is that it mostly "just works" everywhere: it downloads the image which has everything that's needed, it automatically installs dependencies for the tests, and all users running the same (major) verison of ansible-core get the same results. And no collection maintainer has to also maintain requirements.txt files, Makefiles, tox scripts, or nox scripts for it.

It would be a lot easier for everyone if ansible-test would handle most of these things (and have a more extensive configuration side for collections). Then there wouldn't be a need to reinvent the wheel. But considering that the development of ansible-test is kind of frozen (for the collection side), it doesn't look like that will happen anytime soon...

**Comment by oraNod** [comment]
Thanks for the detailed explanation @felixfontein that is helpful. I know I still sort of owe you a 1:1 to explain some of the stuff my team discussed at our F2F session in London a while ago. I think I mentioned that in a comment in some other issue. Essentially we've been looking at available tooling and different means to create collections with a goal of reducing fragmentation (e.g. ansible-creator vs galaxy init vs collection template) and providing a happy path that leads to consistency and quality. This tooling gap certainly aligns with that goal.

@gundalow FYI on this thread. I think this is something we should take a look at and work into our plans. What do you think?

**Comment by gundalow** [comment]
We need to ensure that `ansible-test sanity` doesn't error or return incorrect CI results when run against collections. Though it is OK that Sanity tests more in ansible-core than collections (which this appears to be a case of)

The future of testing is going to be a focus for my team (Ansible Community & Partner Engineering). For those that have been following the [cfgmgmtcamp (3-5 Feb Ghent, Belgium)](https://forum.ansible.com/t/ansible-contributor-summit-at-cfgmgmtcamp-2025/9658), we will have a lot of talks on [DevTools](https://ansible.readthedocs.io/projects/dev-tools/) and I hope we will spent a lot of Wednesday's Contributor Summit talking about the future of collection testing.

My current understand of where we are, is to get more opinionated and [reduce the fragmentation in tooling options](https://forum.ansible.com/t/community-survey-help-us-identify-tooling-used-in-ansible-collection-developers-and-maintainers-community/10502). There is inconsistency and huge wasted effort maintaining different tools.

Red Hat has been working to have ansible-lint as the entry point for multiple testing tools. Ansible-lint is well integrated into [VScode](https://marketplace.visualstudio.com/items?itemName=redhat.ansible), so it's a great user. 

Likewise we want to have [ansible-creator](https://ansible.readthedocs.io/projects/creator/installing/) as the default way to create collections (and be used to create [collection_template](https://github.com/ansible-collections/collection_template).

**Comment by felixfontein** [comment]
Thanks for the pointers! 

I think I'll take a look at adding type hints at a later time, when I have more time to do all the necessary preparations.

**Pull request merged**
