### PR TITLE
Add links.yml file

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Adds docs/docsite/links.yml file as suggested here: https://gist.github.com/felixfontein/18b1763ca2a5320808225c4121b50791

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/links.yml

### CODE REVIEW

**Comment by felixfontein** [comment]
@samccann sounds like a good idea!

**Comment by samccann** [comment]
@felixfontein ok I'll give it a try and point you to the PR

**Comment by felixfontein** [comment]
The collection already uses `antsibull-lint collection-docs` to lint docs/docsite/ (https://github.com/ansible-collections/community.dns/blob/main/tests/sanity/extra/extra-docs.py via https://github.com/ansible-collections/community.dns/blob/main/.github/workflows/extra-tests.yml), so no extra linting step is necessary.

**Comment by felixfontein** [comment]
This file will automatically be linted by existing tests once a new antsibull release is made. I linted it manually, so merging now.

**Comment by felixfontein** [comment]
@samccann thanks for reviewing!

**Pull request merged**
